### PR TITLE
Enable transactions with multiple targets in them

### PR DESCRIPTION
**Pull request by fstromback**
This depends on pull request #49.

It is not yet ready for merge, but I figured this would be a good place to track other issues I found here.

This pull request updates the API to Flowee to properly support transactions with multiple recipients (Flowee gives us all targets, possibly also targets that are not relevant to us). This seems to work, as the old tests still pass.

The problem is a couple of new tests I added. This test is a transaction that submits funds to two invoices. This causes issues since the TxId is a unique, primary key in the database, so one of the invoices are missed.

This test also shows another potential issue: when funds are sent to a transaction in two pieces, there seems to be a race condition. That test (assuming the previous issue is fixed) fails sporadically (rather: succeeds sporadically) indicating some kind of race condition in the system.

These issues are things that you are likely to be able to fix quicker that me @treeman

### CODE REVIEW

**Comment by treeman** [comment]
> This causes issues since the TxId is a unique, primary key in the database, so one of the invoices are missed.

Huh, yeah I didn't think about this case.

> This test also shows another potential issue: when funds are sent to a transaction in two pieces, there seems to be a race condition. That test (assuming the previous issue is fixed) fails sporadically (rather: succeeds sporadically) indicating some kind of race condition in the system.

Hmm, I hope that's just a problem with the test setup, and not something more serious.

Either way, I'll take a look at these.

**Comment by fstromback** [comment]
Sadly, my initial feeling is that it is not only the test setup at play there. Some initial digging showed that both transactions ended up in the database at the end, and were found by the code that computed the total received funds. I also hope it is an artifact of the test setup, that is easier to debug!

**Comment by treeman** [comment]
A few notes:

* Since we're not in release, I didn't bother doing a proper migration. `mix ecto.reset` (with a potential `MIX_ENV` to `test`, a bit weird) will reset the database.
* I altered how we send transaction notifications, to send it the same way Flowee does (one txid with multiple outputs). I also changed the double spend part of it, BUT we don't have any test for that so...
* For confirmations we need a separate "new block at height" message in addition to a "tx confirmed at height" message. Maybe we can change this... But that makes it a bit redundant, and this is already how Flowee (and others) work, so it just makes testing a little more awkward.

**Comment by treeman** [comment]
Oh, I didn't find any race condition after I fixed the other tests, so I assume it's fixed? :)

Also, double-spending tests/fixtures are tracked here: https://github.com/bitpal/bitpal/issues/45 Maybe that's something you could take a quick look at? I don't remember what other things you wanted to do...

Is there anything else this PR should do, or can we merge it now?

**Comment by fstromback** [comment]
Let's hope it was an artifact of the other issues! I will run the tests on my machine as well and see if I can replicate it there.

We get "new block at height" messages from Flowee already. The Flowee module even subscribes to them if I remember correctly. Or do you mean something else regarding your last point?

The other thing I wanted to do here was to add a function for finding transactions (either by txid or by target address) in a particular block, so that we can look back in case some part of the system was down and missed some notifications. But if this works now, it is better if you merge this PR and I start a new one for that.

As a sidenote, I also have code for checking the Flowee version. I will create a PR for that soon.

**Comment by fstromback** [comment]
Hmmm... As I wrote the previous comment, GitHub's CI seemed to re-run some checks, and linked me to a run where the "race condition" test case failed. When I went back to this page, all was good again, so I don't know if GitHub accidentally showed me an old run for a while, or if it actually did re-run the CI job...

Anyway, we will find out if that test is flaky for some reason as we will run the test suite quite a few times.

**Pull request merged**
